owner: flother
repo: upptime
sites:
  - name: Flother
    url: https://www.flother.is
    icon: https://www.flother.is/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 2000
assignees:
  - flother
status-website:
  name: Upptime
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  navbar:
    - title: Flother
      href: https://www.flother.is/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
